language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7


services:
  - mongodb
  - rabbitmq

cache:
  directories:
  - $HOME/.m2

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'


script:
  - mvn test
