/*
* Generated file
*
* Generated from: yang module name: netshell-odlcorsa-impl yang module local name: netshell-odlcorsa-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Sep 11 11:34:06 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package net.es.netshell.odlcorsa.impl;
public class OdlCorsaModuleFactory extends net.es.netshell.odlcorsa.impl.AbstractOdlCorsaModuleFactory {

}
