/*
* Generated file
*
* Generated from: yang module name: netshell-odlmdsal-impl yang module local name: netshell-odlmdsal-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 21 14:42:44 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package net.es.netshell.odlmdsal.impl;
/**
* NetShell ODL MD-SAL integration
*/
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2015-08-07", name = "netshell-odlmdsal-impl", namespace = "urn:opendaylight:params:xml:ns:yang:netshell-odlmdsal:impl")

@org.opendaylight.controller.config.api.annotations.Description(value="NetShell ODL MD-SAL integration")
public abstract class AbstractOdlMdsalModuleFactory implements org.opendaylight.controller.config.spi.ModuleFactory {
    public static final java.lang.String NAME = "netshell-odlmdsal-impl";

    private static final java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs;

    @Override
    public final String getImplementationName() {
        return NAME;
    }

    static {
        java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs2 = new java.util.HashSet<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>>();
        serviceIfcs = java.util.Collections.unmodifiableSet(serviceIfcs2);
    }

    @Override
    public final boolean isModuleImplementingServiceInterface(Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface> serviceInterface) {
        for (Class<?> ifc: serviceIfcs) {
            if (serviceInterface.isAssignableFrom(ifc)){
                return true;
            }
        }
        return false;
    }

    @Override
    public java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> getImplementedServiceIntefaces() {
        return serviceIfcs;
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return instantiateModule(instanceName, dependencyResolver, bundleContext);
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.opendaylight.controller.config.api.DynamicMBeanWithInstance old, org.osgi.framework.BundleContext bundleContext) throws Exception {
        net.es.netshell.odlmdsal.impl.OdlMdsalModule oldModule = null;
        try {
            oldModule = (net.es.netshell.odlmdsal.impl.OdlMdsalModule) old.getModule();
        } catch(Exception e) {
            return handleChangedClass(old);
        }
        net.es.netshell.odlmdsal.impl.OdlMdsalModule module = instantiateModule(instanceName, dependencyResolver, oldModule, old.getInstance(), bundleContext);
        module.setNotificationService(oldModule.getNotificationService());
        module.setRpcRegistry(oldModule.getRpcRegistry());
        module.setDataBroker(oldModule.getDataBroker());

        return module;
    }

    public net.es.netshell.odlmdsal.impl.OdlMdsalModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, net.es.netshell.odlmdsal.impl.OdlMdsalModule oldModule, java.lang.AutoCloseable oldInstance, org.osgi.framework.BundleContext bundleContext) {
        return new net.es.netshell.odlmdsal.impl.OdlMdsalModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver, oldModule, oldInstance);
    }

    public net.es.netshell.odlmdsal.impl.OdlMdsalModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return new net.es.netshell.odlmdsal.impl.OdlMdsalModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver);
    }

    public net.es.netshell.odlmdsal.impl.OdlMdsalModule handleChangedClass(org.opendaylight.controller.config.api.DynamicMBeanWithInstance old) throws Exception {
        throw new UnsupportedOperationException("Class reloading is not supported");
    }

    @Override
    public java.util.Set<net.es.netshell.odlmdsal.impl.OdlMdsalModule> getDefaultModules(org.opendaylight.controller.config.api.DependencyResolverFactory dependencyResolverFactory, org.osgi.framework.BundleContext bundleContext) {
        return new java.util.HashSet<net.es.netshell.odlmdsal.impl.OdlMdsalModule>();
    }

}
